jobs:
  include:
    - stage mar-rover
      language: python
      python:
      - "2.7"
      - "3.6"
    # command to install dependencies
      install:
        - pip install -r mars-rover\python\requirements.txt
      script:
        - pytest mars-rover\python\test_mars_rover.py --cov=mars-rover/python/
      after_success:
        - coveralls